language: node_js

deploy:
  provider: cloudfoundry
  api: $CF_API
  username: $CF_LOGIN
  password: $CF_PASS
  organization: $CF_ORG
  space: $CF_SPACE
  on:
    repo: AntonAleksandrov/sdk-status-monitor
